version: '3.1'
services:
  subdomain:
    image: hb0730/subdoamin
    restart: always
    container_name: subdomain
    ports:
      - 80:80
    networks:
      - docker-net
networks:
  docker-net:
    external: true